workflows:
  android:
    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/mapping.txt
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    cache:
      cache_paths:
        - ~/.npm
        - ~/.gradle/caches
        - ~/.android/build-cache
    environment:
      groups:
        - google_credentials
      android_signing:
        - codemagic
      vars:
        PACKAGE_NAME: 'com.speedyairhockey'
        MYAPP_UPLOAD_STORE_FILE: 'codemagic.keystore'
        MYAPP_UPLOAD_STORE_PASSWORD: $CM_KEYSTORE_PASSWORD
        MYAPP_UPLOAD_KEY_ALIAS: $CM_KEY_ALIAS
        MYAPP_UPLOAD_KEY_PASSWORD: $CM_KEY_PASSWORD
    scripts:
      - name: Install npm dependencies
        script: npm ci --verbose
      - name: Expo Android prebuild
        script: npx expo prebuild --platform android
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Copy keystore to android directory
        script: |
          cp codemagic.keystore android/app/
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
      - name: Build Android App Bundle
        script: |
          cd android
          ./gradlew bundleRelease
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
    triggering:
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: true
      events:
        - push
  ios:
    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - build/ios/ipa/*.ipa
    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods
    environment:
      groups:
        - app_store_credentials
        - github_credentials
        - gitlab_credentials
      ios_signing:
        bundle_identifier: com.speedyairhockey
        distribution_type: app_store
      vars:
        APP_STORE_APPLE_ID: 6751126539
        BUNDLE_ID: 'com.speedyairhockey'
        XCODE_SCHEME: 'SpeedyAirHockey'
        XCODE_WORKSPACE: 'SpeedyAirHockey.xcworkspace'
    integrations:
      app_store_connect: AuthKey_WTD5M2963K
    name: iOS
    publishing:
      app_store_connect:
        auth: integration
        cancel_previous_submissions: true
        submit_to_app_store: true
    scripts:
      - name: Install npm dependencies
        script: npm ci --verbose
      - name: Increment build number
        script: |
          set -e
          chmod +x ./scripts/update_ios_build_number.sh
          ./scripts/update_ios_build_number.sh
      - name: Expo iOS prebuild
        script: npx expo prebuild --platform ios
      - name: Set Info.plist values
        script: |
          PLIST=$CM_BUILD_DIR/ios/$XCODE_SCHEME/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles --code-signing-setup-verbose-logging --warn-only -v
      - name: Build ipa for distribution
        script: xcode-project build-ipa --scheme "$XCODE_SCHEME" --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" -v
    triggering:
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: true
      events:
        - push
